spring.application.name=workcount
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

ss.policy.entry-time=07:30
ss.policy.departure-time-default=19:30
ss.policy.departure-time-friday=16:30
ss.policy.target-weekly-hours=PT37H30M

